server:
  port: 8888
  
spring:  profiles:    active: native
  cloud:    config:      server:        native:          search-locations: ../microservices/config
          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka