server:
  port: 8888
spring:  cloud:    config:      server:        git:
          uri: https://github.com/RedHandStudio/spring-cloud-challenge-repo
          default-label: main          search-paths: distancia,monolito,pagamento