server:
  port: 8081

spring:
  application:
    name: 'eats-pagamento'

configuracao:
  monolito:
    url: http://localhost:8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka